Correctly specify the pip cache in the Github workflow.
Every single run of the `upload-to-pypi` task, I would see:

    Post job cleanup.
    Error: Unexpected end of JSON input

and I had no idea why. But looking at the `setup-python` step:

    cache: pip
    cache-dependency-path: python-spec/requirements-py.txt
    check-latest: false
    token: ***
    update-environment: true

There is no `requirements-py.txt` file, because there is no `matrix`
to get a `matrix.python-version` from, because it's not a matrixed step.